#!/usr/bin/env python3
"""Regenerate the pinned Unicode 17.0.0 simple-fold table, without networking."""
from pathlib import Path
import hashlib

HERE = Path(__file__).resolve().parent
SOURCE = HERE / "CaseFolding-17.0.0.txt"
SHA256 = "ff8d8fefbf123574205085d6714c36149eb946d717a0c585c27f0f4ef58c4183"
raw = SOURCE.read_bytes()
assert hashlib.sha256(raw).hexdigest() == SHA256, "Pinned Unicode data changed"
pairs = []
for line in raw.decode().splitlines():
    fields = line.split("#", 1)[0].strip().split(";")
    if len(fields) >= 3 and fields[1].strip() in {"C", "S"}:
        targets = fields[2].split()
        assert len(targets) == 1
        pairs.append((int(fields[0], 16), int(targets[0], 16)))
assert pairs == sorted(set(pairs))
assert len({source for source, target in pairs}) == len(pairs)
mapping = dict(pairs)
assert all(mapping.get(target, target) == target for target in mapping.values())
header = f'''// @generated by unicode/generate.py; do not hand-edit.
// Unicode 17.0.0 CaseFolding.txt C + S mappings only, excluding F and T.
// Source: https://www.unicode.org/Public/17.0.0/ucd/CaseFolding.txt
// SHA-256: {SHA256}
// Copyright Unicode, Inc. Distributed under adjacent unicode/LICENSE-UNICODE.
// {len(pairs)} idempotent single-scalar mappings. Unlisted scalars map to themselves.

#[rustfmt::skip]
pub(super) const SIMPLE_CASE_FOLD: &[(char, char)] = &[
'''
rows = []
for offset in range(0, len(pairs), 4):
    rows.append("    " + " ".join(f"('\\u{{{a:x}}}', '\\u{{{b:x}}}')," for a, b in pairs[offset:offset+4]))
output = header + "\n".join(rows) + "\n];\n"
(HERE.parent / "case_fold_data.rs").write_text(output)
print(f"Generated {len(pairs)} simple fold mappings from {SHA256}")
